# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - ${PORT_DOCKER_MONGODB}:27017
    volumes:
       - ./dataMongoDB:/data/db/

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${PORT_MONGO_EXPLRESS}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example